FROM node:22.12.0-alpine AS ui-builder
WORKDIR /root
COPY ui/index.html ui/eslint.config.js ui/package.json ui/package-lock.json ui/vite.config.js /root/
COPY ui/src /root/src/
COPY ui/public /root/public/
RUN npm install && npm run build

FROM python:3.13.2-alpine
LABEL organization="cpnet"
LABEL maintainer="Weihong Guan <weihong.guan@cpnet.io>"

RUN mkdir -p /root/app/public /root/usr/

WORKDIR /root/app

COPY api-fastapi/.env api-fastapi/pyproject.toml api-fastapi/README.md api-fastapi/RELEASES.md api-fastapi/requirements.txt /root/app/
COPY api-fastapi/src /root/app/src

COPY --from=ui-builder /root/dist /root/app/public/

RUN pip install -r requirements.txt

ENV APP_ENV=production
CMD ["python", "src/main.py"]
